name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    name: Deploy Mkdocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master